include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule
    require_trailing_commas: true
    sort_constructors_first: true
    public_member_api_docs: true
    always_use_package_imports: true
    avoid_returning_null_for_future: true
    avoid_multiple_declarations_per_line: true
# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
